### ISSUE TITLE
jumploader-glorious_gmmk - reboot to firmware

### ISSUE THREAD

**Issue by infinitevalence** [SonixQMK/sonix-keyboard-bootloader#13]
after flashing the jumploader-glorious_gmmk.bin when I hold FN+ESC the keyboard will reboot but does not enter bootloader mode.

GMMK Full v2 SN32F2x

**Comment by gloryhzw** [comment]
u have to press ENTER too...FN+ESC = reboot, ENTER = BL mode

**Comment by coolspot18** [comment]
FN+ESC reboots the board, but Enter doesn't seem to get into the bootloader? No matter how I press Enter, I can't get the bootloader to kick in?

**Comment by L4R63N7** [comment]
I'm having the same problem. Fn+esc reboots the keyboard, but holding Enter doesn't enter bootloader. I can get into bootloader by shorting the boot pin to ground but it never works with key presses.

**Comment by nwaelti** [comment]
If someone still has this problem:
The way to get into the bootloader is effectiely with ENTER key, holding it down AND WHILE it's down hitting Fn+ESC

**Comment by L4R63N7** [comment]
> If someone still has this problem: The way to get into the bootloader is effectiely with ENTER key, holding it down AND WHILE it's down hitting Fn+ESC

This is exactly what I'm trying but it doesn't work. The keyboard reboots but not into bootloader mode.

**Comment by nwaelti** [comment]
Okay, with a build from the current s32_master if is now working (at least on my machine), I'm using a GMMK Full
