### ISSUE TITLE
Pre-Compiled Jumploaders have expired?

### ISSUE THREAD

**Issue by tomlawnmower** [SonixQMK/sonix-keyboard-bootloader#19]
Hello, I can't seem to find any available downloads for the pre-compiled jumploaders when navigating to 
`Releases` or `Actions > Add Keychron K7 White (SN32F260) (#15) > scroll down to artifacts`. Is it possible to run another CI workflow to build new pre-compiled jumploaders? Or if the downloads have been moved somewhere else, I apologize for being dumb and unable to find it, and would really appreciate it if you could point me in the right direction. 

I stumbled on this repo today (from https://www.youtube.com/watch?v=aUiKHdI5Vk8), and I'm super excited to try out QMK on the gmmk. A massive thank you to everyone who has been working on this project!

**Comment by dexter93** [comment]
Fixed with [Latest Release](https://github.com/SonixQMK/sonix-keyboard-bootloader/releases/latest)
