### ISSUE TITLE
File expired 

### ISSUE THREAD

**Issue by Shankeyyyy** [SonixQMK/sonix-keyboard-bootloader#21]
Pre-Compiled Jumploaders in not work file download, i want to try in my keyboard k582 pro

**Comment by TheLinuxTrucker** [comment]
For anyone who comes across this in the future, there is a pretty easy way to run this using your own fork. At the top of the repo, fork this to your account. Then clone the repo to your local machine, create a random text file in the cloned directory. Commit the text file and push the changes back to github. This repo is setup to run on pushes. So, the action will run and you will have a brand new, compiled on your repo version of the file you are looking for.

**Comment by brendeni1** [comment]
> For anyone who comes across this in the future, there is a pretty easy way to run this using your own fork. At the top of the repo, fork this to your account. Then clone the repo to your local machine, create a random text file in the cloned directory. Commit the text file and push the changes back to github. This repo is setup to run on pushes. So, the action will run and you will have a brand new, compiled on your repo version of the file you are looking for.

Bloody legend.

**Comment by HackintoshwithUbuntu** [comment]
To people coming across this further into the future, Github has deprecated some of the old apis so you will need to go in and make a small update to the Github actions code.
Go to /.github/workflows/auto_build.yml and update both the things that say 'v2' to 'v4', just a simple find and replace is fine.

**Comment by dexter93** [comment]
Fixed with [Latest Release](https://github.com/SonixQMK/sonix-keyboard-bootloader/releases/latest)
